//
//  ObjectID.swift
//  PostgreSQL
//

import CLibPQ

private let customOIDMinValue: Oid  = 16_000

public enum ObjectID: Oid {
	case CustomType                 = 00_000
	case Unknown                    = 00_705
	
	case SmallInt                   = 00_021
	case Int                        = 00_023
	case BigInt                     = 00_020
	case Numeric                    = 01_700
	case Real                       = 00_700
	case Double                     = 00_701
	case Money                      = 00_790
	case VarChar                    = 01_043
	case Char                       = 01_042
	case Text                       = 00_025
	case ByteArray                  = 00_017
	case Timestamp                  = 01_114
	case TimestampWithTimezone      = 01_184
	case Date                       = 01_082
	case Time                       = 01_083
	case TimeWithTimezone           = 01_266
	case TimeInterval               = 01_186
	case Boolean                    = 00_016
	case Point                      = 00_600
	case Line                       = 00_628
	case LineSegment                = 00_601
	case Box                        = 00_603
	case Path                       = 00_602
	case Polygon                    = 00_604
	case Circle                     = 00_718
	case Network                    = 00_650
	case IPAddress                  = 00_869
	case MACAddress                 = 00_829
	case BitString                  = 01_560
	case TextSearchVector           = 03_614
	case TextSearchQuery            = 03_615
	case UUID                       = 02_950
	case XML                        = 00_142
	case JSON                       = 00_114
	case JSONB                      = 03_802
	case Int32Range                 = 03_904
	case Int64Range                 = 03_926
	case NumericRange               = 03_906
	case TimestampRange             = 03_908
	case TimeRange                  = 03_910
	case DateRange                  = 03_912
	case oid                        = 00_026
	case regproc                    = 00_024
	case regprocedure               = 02_202
	case regoper                    = 02_203
	case regoperator                = 02_204
	case regclass                   = 02_205
	case regtype                    = 02_206
	case regrole                    = 04_096
	case regnamespace               = 04_089
	case regconfig                  = 03_734
	case regdictionary              = 03_769
	case LogSequenceNumber          = 03_220
	
	case SmallIntArray              = 01_005
	case IntArray                   = 01_007
	case BigIntArray                = 01_016
	case NumericArray               = 01_231
	case RealArray                  = 01_021
	case DoubleArray                = 01_022
	case MoneyArray                 = 00_791
	case VarCharArray               = 01_015
	case CharArray                  = 01_014
	case TextArray                  = 01_009
	case ByteArrayArray             = 01_001
	case TimestampArray             = 01_115
	case TimestampWithTimezoneArray = 01_185
	case DateArray                  = 01_182
	case TimeArray                  = 01_183
	case TimeWithTimezoneArray      = 01_270
	case TimeIntervalArray          = 01_187
	case BooleanArray               = 01_000
	case PointArray                 = 01_017
	case LineArray                  = 00_629
	case LineSegmentArray           = 01_018
	case BoxArray                   = 01_020
	case PathArray                  = 01_019
	case PolygonArray               = 01_027
	case CircleArray                = 00_719
	case NetworkArray               = 00_651
	case IPAddressArray             = 01_041
	case MACAddressArray            = 01_040
	case BitStringArray             = 01_561
	case TextSearchVectorArray      = 03_643
	case TextSearchQueryArray       = 03_645
	case UUIDArray                  = 02_951
	case XMLArray                   = 00_143
	case JSONArray                  = 00_199
	case JSONBArray                 = 03_807
	case Int32RangeArray            = 03_905
	case Int64RangeArray            = 03_927
	case NumericRangeArray          = 03_907
	case TimestampRangeArray        = 03_909
	case TimeRangeArray             = 03_911
	case DateRangeArray             = 03_913
	case oidArray                   = 01_028
	case regprocArray               = 01_008
	case regprocedureArray          = 02_207
	case regoperArray               = 02_208
	case regoperatorArray           = 02_209
	case regclassArray              = 02_210
	case regtypeArray               = 02_211
	case regroleArray               = 04_097
	case regnamespaceArray          = 04_090
	case regconfigArray             = 03_735
	case regdictionaryArray         = 03_770
	case LogSequenceNumberArray     = 03_221
	
	public init?(rawValue: Oid) {
		switch rawValue {
			case let value where value > customOIDMinValue:    self = .CustomType
			case ObjectID.Unknown.rawValue:                    self = .Unknown
			case ObjectID.SmallInt.rawValue:                   self = .SmallInt
			case ObjectID.Int.rawValue:                        self = .Int
			case ObjectID.BigInt.rawValue:                     self = .BigInt
			case ObjectID.Numeric.rawValue:                    self = .Numeric
			case ObjectID.Real.rawValue:                       self = .Real
			case ObjectID.Double.rawValue:                     self = .Double
			case ObjectID.Money.rawValue:                      self = .Money
			case ObjectID.VarChar.rawValue:                    self = .VarChar
			case ObjectID.Char.rawValue:                       self = .Char
			case ObjectID.Text.rawValue:                       self = .Text
			case ObjectID.ByteArray.rawValue:                  self = .ByteArray
			case ObjectID.Timestamp.rawValue:                  self = .Timestamp
			case ObjectID.TimestampWithTimezone.rawValue:      self = .TimestampWithTimezone
			case ObjectID.Date.rawValue:                       self = .Date
			case ObjectID.Time.rawValue:                       self = .Time
			case ObjectID.TimeWithTimezone.rawValue:           self = .TimeWithTimezone
			case ObjectID.TimeInterval.rawValue:               self = .TimeInterval
			case ObjectID.Boolean.rawValue:                    self = .Boolean
			case ObjectID.Point.rawValue:                      self = .Point
			case ObjectID.Line.rawValue:                       self = .Line
			case ObjectID.LineSegment.rawValue:                self = .LineSegment
			case ObjectID.Box.rawValue:                        self = .Box
			case ObjectID.Path.rawValue:                       self = .Path
			case ObjectID.Polygon.rawValue:                    self = .Polygon
			case ObjectID.Circle.rawValue:                     self = .Circle
			case ObjectID.Network.rawValue:                    self = .Network
			case ObjectID.IPAddress.rawValue:                  self = .IPAddress
			case ObjectID.MACAddress.rawValue:                 self = .MACAddress
			case ObjectID.BitString.rawValue:                  self = .BitString
			case ObjectID.TextSearchVector.rawValue:           self = .TextSearchVector
			case ObjectID.TextSearchQuery.rawValue:            self = .TextSearchQuery
			case ObjectID.UUID.rawValue:                       self = .UUID
			case ObjectID.XML.rawValue:                        self = .XML
			case ObjectID.JSON.rawValue:                       self = .JSON
			case ObjectID.JSONB.rawValue:                      self = .JSONB
			case ObjectID.Int32Range.rawValue:                 self = .Int32Range
			case ObjectID.Int64Range.rawValue:                 self = .Int64Range
			case ObjectID.NumericRange.rawValue:               self = .NumericRange
			case ObjectID.TimestampRange.rawValue:             self = .TimestampRange
			case ObjectID.TimeRange.rawValue:                  self = .TimeRange
			case ObjectID.DateRange.rawValue:                  self = .DateRange
			case ObjectID.oid.rawValue:                        self = .oid
			case ObjectID.regproc.rawValue:                    self = .regproc
			case ObjectID.regprocedure.rawValue:               self = .regprocedure
			case ObjectID.regoper.rawValue:                    self = .regoper
			case ObjectID.regoperator.rawValue:                self = .regoperator
			case ObjectID.regclass.rawValue:                   self = .regclass
			case ObjectID.regtype.rawValue:                    self = .regtype
			case ObjectID.regrole.rawValue:                    self = .regrole
			case ObjectID.regnamespace.rawValue:               self = .regnamespace
			case ObjectID.regconfig.rawValue:                  self = .regconfig
			case ObjectID.regdictionary.rawValue:              self = .regdictionary
			case ObjectID.LogSequenceNumber.rawValue:          self = .LogSequenceNumber
			
			case ObjectID.SmallIntArray.rawValue:              self = .SmallIntArray
			case ObjectID.IntArray.rawValue:                   self = .IntArray
			case ObjectID.BigIntArray.rawValue:                self = .BigIntArray
			case ObjectID.NumericArray.rawValue:               self = .NumericArray
			case ObjectID.RealArray.rawValue:                  self = .RealArray
			case ObjectID.DoubleArray.rawValue:                self = .DoubleArray
			case ObjectID.MoneyArray.rawValue:                 self = .MoneyArray
			case ObjectID.VarCharArray.rawValue:               self = .VarCharArray
			case ObjectID.CharArray.rawValue:                  self = .CharArray
			case ObjectID.TextArray.rawValue:                  self = .TextArray
			case ObjectID.ByteArrayArray.rawValue:             self = .ByteArrayArray
			case ObjectID.TimestampArray.rawValue:             self = .TimestampArray
			case ObjectID.TimestampWithTimezoneArray.rawValue: self = .TimestampWithTimezoneArray
			case ObjectID.DateArray.rawValue:                  self = .DateArray
			case ObjectID.TimeArray.rawValue:                  self = .TimeArray
			case ObjectID.TimeWithTimezoneArray.rawValue:      self = .TimeWithTimezoneArray
			case ObjectID.TimeIntervalArray.rawValue:          self = .TimeIntervalArray
			case ObjectID.BooleanArray.rawValue:               self = .BooleanArray
			case ObjectID.PointArray.rawValue:                 self = .PointArray
			case ObjectID.LineArray.rawValue:                  self = .LineArray
			case ObjectID.LineSegmentArray.rawValue:           self = .LineSegmentArray
			case ObjectID.BoxArray.rawValue:                   self = .BoxArray
			case ObjectID.PathArray.rawValue:                  self = .PathArray
			case ObjectID.PolygonArray.rawValue:               self = .PolygonArray
			case ObjectID.CircleArray.rawValue:                self = .CircleArray
			case ObjectID.NetworkArray.rawValue:               self = .NetworkArray
			case ObjectID.IPAddressArray.rawValue:             self = .IPAddressArray
			case ObjectID.MACAddressArray.rawValue:            self = .MACAddressArray
			case ObjectID.BitStringArray.rawValue:             self = .BitStringArray
			case ObjectID.TextSearchVectorArray.rawValue:      self = .TextSearchVectorArray
			case ObjectID.TextSearchQueryArray.rawValue:       self = .TextSearchQueryArray
			case ObjectID.UUIDArray.rawValue:                  self = .UUIDArray
			case ObjectID.XMLArray.rawValue:                   self = .XMLArray
			case ObjectID.JSONArray.rawValue:                  self = .JSONArray
			case ObjectID.JSONBArray.rawValue:                 self = .JSONBArray
			case ObjectID.Int32RangeArray.rawValue:            self = .Int32RangeArray
			case ObjectID.Int64RangeArray.rawValue:            self = .Int64RangeArray
			case ObjectID.NumericRangeArray.rawValue:          self = .NumericRangeArray
			case ObjectID.TimestampRangeArray.rawValue:        self = .TimestampRangeArray
			case ObjectID.TimeRangeArray.rawValue:             self = .TimeRangeArray
			case ObjectID.DateRangeArray.rawValue:             self = .DateRangeArray
			case ObjectID.oidArray.rawValue:                   self = .oidArray
			case ObjectID.regprocArray.rawValue:               self = .regprocArray
			case ObjectID.regprocedureArray.rawValue:          self = .regprocedureArray
			case ObjectID.regoperArray.rawValue:               self = .regoperArray
			case ObjectID.regoperatorArray.rawValue:           self = .regoperatorArray
			case ObjectID.regclassArray.rawValue:              self = .regclassArray
			case ObjectID.regtypeArray.rawValue:               self = .regtypeArray
			case ObjectID.regroleArray.rawValue:               self = .regroleArray
			case ObjectID.regnamespaceArray.rawValue:          self = .regnamespaceArray
			case ObjectID.regconfigArray.rawValue:             self = .regconfigArray
			case ObjectID.regdictionaryArray.rawValue:         self = .regdictionaryArray
			case ObjectID.LogSequenceNumberArray.rawValue:     self = .LogSequenceNumberArray
			default: return nil
		}
	}
}
